package testsSelenium;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import es.uma.informatica.sii.anotaciones.Requisitos;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GrupoIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  
  private static final String UNIDAD_PERSITENCIA_PRUEBAS = "SecretariaPU";
  
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    
    BaseDatos.inicializaBaseDatos(UNIDAD_PERSITENCIA_PRUEBAS);
    
  }
  
  @After
  public void tearDown() {
    driver.quit();
  }
  
  @Requisitos({"RF4"})
  @Test
  public void cRUDGrupo() {
    driver.get("http://localhost:8080/Secretaria-war/");
    driver.manage().window().setSize(new Dimension(1255, 794));
    driver.findElement(By.id("inicioSesion:usuario")).click();
    driver.findElement(By.id("inicioSesion:usuario")).sendKeys("admin");
    driver.findElement(By.id("inicioSesion:password")).sendKeys("admin");
    driver.findElement(By.id("inicioSesion:botonInicioSesion")).click();
    driver.findElement(By.cssSelector("td:nth-child(2) > .centrado")).click();
    driver.findElement(By.id("botonImportarTitulaciones")).click();
    driver.findElement(By.id("Titulaciones:archivotitulaciones:filetitulaciones")).sendKeys("/home/alumno/eclipse-workspace/Secretaria/Secretaria-ejb/src/test/resources/Titulacion.csv");
    driver.findElement(By.id("Titulaciones:importarTitulacion")).click();
    driver.findElement(By.id("botonImportarUsuarios")).click();
    driver.findElement(By.id("Grupos:crearGrupos")).click();
    driver.findElement(By.id("botonImportarUsuarios")).click();
    driver.findElement(By.cssSelector("td:nth-child(2) > .centrado")).click();
    driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(1)")).getText(), is("1041"));
    driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(2)")).getText(), is("1"));
    driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(3)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(3)")).getText(), is("A"));
    driver.findElement(By.id("Grupos:j_idt11:0:botonEliminarGrupo")).click();
    driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(1)")).getText(), is("1041"));
    driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(2)")).getText(), is("2"));
    driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(3)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(3)")).getText(), is("A"));
    driver.findElement(By.id("Grupos:j_idt11:0:botonModificarGrupo")).click();
    driver.findElement(By.id("modificarGrupo:letra")).click();
    driver.findElement(By.id("modificarGrupo:letra")).sendKeys("D");
    driver.findElement(By.id("modificarGrupo:botonModificar")).click();
    driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(1)")).getText(), is("1041"));
    driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(2)")).getText(), is("2"));
    driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(3)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(3)")).getText(), is("D"));
    driver.findElement(By.cssSelector("td:nth-child(3) > .centrado")).click();
    driver.findElement(By.id("j_idt15:botonCerrarSesion")).click();
  }
}
