package testsSelenium;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import es.uma.informatica.sii.anotaciones.Requisitos;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class VerimportarfiltrarIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  
  private static final String UNIDAD_PERSITENCIA_PRUEBAS = "SecretariaPU";
  
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    
    BaseDatos.inicializaBaseDatos(UNIDAD_PERSITENCIA_PRUEBAS);
    
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  
  @Requisitos({"RF7","RF11","RF18"})
  @Test
  public void verimportarfiltrar() {
    driver.get("http://localhost:8080/Secretaria-war/");
    driver.manage().window().setSize(new Dimension(1573, 925));
    driver.findElement(By.id("inicioSesion:usuario")).click();
    driver.findElement(By.id("inicioSesion:usuario")).sendKeys("admin");
    driver.findElement(By.id("inicioSesion:password")).sendKeys("admin");
    driver.findElement(By.id("inicioSesion:botonInicioSesion")).click();
    driver.findElement(By.cssSelector("td:nth-child(2) > .centrado")).click();
    driver.findElement(By.id("botonImportarAlumnos")).click();
    driver.findElement(By.id("Alumnos:archivoalumnos:filealumnos")).sendKeys("/home/alumno/eclipse-workspace/Secretaria/Secretaria-ejb/src/test/resources/alumnos.csv");
    driver.findElement(By.id("Alumnos:importarAlumno")).click();
    driver.findElement(By.id("botonImportarAlumnos")).click();
    driver.findElement(By.cssSelector("td:nth-child(3) > .centrado")).click();
    driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(1)")).getText(), is("95115697E"));
    driver.findElement(By.id("Alumnos:dni")).click();
    driver.findElement(By.id("Alumnos:dni")).sendKeys("125678A");
    driver.findElement(By.id("Alumnos:botonBuscarAlumno")).click();
    driver.findElement(By.cssSelector("tbody:nth-child(2) td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) td:nth-child(1)")).getText(), is("125678A"));
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tbody:nth-child(3) td:nth-child(1)"));
      assert(elements.size() == 0);
    }
    driver.findElement(By.cssSelector("td:nth-child(4) > .centrado")).click();
    driver.findElement(By.id("botonTitulaciones")).click();
    driver.findElement(By.cssSelector("td:nth-child(4) > .centrado")).click();
    driver.findElement(By.cssSelector("table:nth-child(2) td:nth-child(1) > .centrado")).click();
    driver.findElement(By.cssSelector("td:nth-child(2) > .centrado")).click();
    driver.findElement(By.id("botonImportarTitulaciones")).click();
    driver.findElement(By.id("Titulaciones:archivotitulaciones:filetitulaciones")).sendKeys("/home/alumno/eclipse-workspace/Secretaria/Secretaria-ejb/src/test/resources/Titulacion.csv");
    driver.findElement(By.id("Titulaciones:importarTitulacion")).click();
    driver.findElement(By.id("botonImportarTitulaciones")).click();
    driver.findElement(By.cssSelector("td:nth-child(3) > .centrado")).click();
    driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(1)")).getText(), is("1041"));
    driver.findElement(By.id("Titulaciones:Titulacion")).click();
    driver.findElement(By.id("Titulaciones:Titulacion")).sendKeys("1234");
    driver.findElement(By.id("Titulaciones:botonBuscarTitulacion")).click();
    driver.findElement(By.cssSelector("tbody:nth-child(2) td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) td:nth-child(1)")).getText(), is("1234"));
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tbody:nth-child(3) td:nth-child(1)"));
      assert(elements.size() == 0);
    }
    driver.findElement(By.cssSelector("td:nth-child(3) > .centrado")).click();
    driver.findElement(By.cssSelector("td:nth-child(4) > .centrado")).click();
    driver.findElement(By.cssSelector("table:nth-child(2) td:nth-child(1) > .centrado")).click();
    driver.findElement(By.cssSelector("td:nth-child(2) > .centrado")).click();
    driver.findElement(By.id("botonImportarAsignaturas")).click();
    driver.findElement(By.id("Asignaturas:archivoasignaturas:fileasignaturas")).sendKeys("/home/alumno/eclipse-workspace/Secretaria/Secretaria-ejb/src/test/resources/Oferta asignaturas.xlsx");
    driver.findElement(By.id("Asignaturas:importarAsignatura")).click();
    driver.findElement(By.id("botonImportarAsignaturas")).click();
    driver.findElement(By.cssSelector("td:nth-child(3) > .centrado")).click();
    driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(1)")).getText(), is("12345"));
    driver.findElement(By.cssSelector("tr:nth-child(4) > td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > td:nth-child(1)")).getText(), is("50659"));
    driver.findElement(By.id("Asignaturas:Referencia")).click();
    driver.findElement(By.id("Asignaturas:Referencia")).sendKeys("12346");
    driver.findElement(By.id("Asignaturas:botonBuscarAsignatura")).click();
    driver.findElement(By.cssSelector("tbody:nth-child(2) td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) td:nth-child(1)")).getText(), is("12346"));
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tbody:nth-child(3) td:nth-child(1)"));
      assert(elements.size() == 0);
    }
    driver.findElement(By.cssSelector("td:nth-child(3) > .centrado")).click();
    driver.findElement(By.cssSelector("td:nth-child(4) > .centrado")).click();
    driver.findElement(By.cssSelector("table:nth-child(2) td:nth-child(1) > .centrado")).click();
    driver.findElement(By.cssSelector("td:nth-child(2) > .centrado")).click();
    driver.findElement(By.id("botonImportarExpedientes")).click();
    driver.findElement(By.id("Expedientes:archivoexpedientes:fileexpedientes")).sendKeys("/home/alumno/eclipse-workspace/Secretaria/Secretaria-ejb/src/test/resources/alumnos.csv");
    driver.findElement(By.id("Expedientes:importarExpediente")).click();
    driver.findElement(By.id("botonImportarExpedientes")).click();
    driver.findElement(By.cssSelector("td:nth-child(3) > .centrado")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(1)")).getText(), is("104100002"));
    driver.findElement(By.id("Expedientes:Num_Exp")).click();
    driver.findElement(By.id("Expedientes:Num_Exp")).sendKeys("123");
    driver.findElement(By.id("Expedientes:botonBuscarExpediente")).click();
    driver.findElement(By.cssSelector("tbody:nth-child(2) td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) td:nth-child(1)")).getText(), is("123"));
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tbody:nth-child(3) td:nth-child(1)"));
      assert(elements.size() == 0);
    }
    driver.findElement(By.cssSelector("td:nth-child(3) > .centrado")).click();
    driver.findElement(By.cssSelector("td:nth-child(4) > .centrado")).click();
    driver.findElement(By.cssSelector("table:nth-child(2) td:nth-child(1) > .centrado")).click();
    driver.findElement(By.cssSelector("td:nth-child(2) > .centrado")).click();
    driver.findElement(By.id("botonImportarMatriculas")).click();
    driver.findElement(By.id("Matriculas:archivomatriculas:filematriculas")).sendKeys("/home/alumno/eclipse-workspace/Secretaria/Secretaria-ejb/src/test/resources/alumnos.csv");
    driver.findElement(By.id("Matriculas:importarMatricula")).click();
    driver.findElement(By.cssSelector("table:nth-child(2) td:nth-child(1) > .centrado")).click();
    driver.findElement(By.cssSelector("table:nth-child(1) td:nth-child(1) > .centrado")).click();
    driver.findElement(By.id("botonMatriculas")).click();
    driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(2) > td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(2) > td:nth-child(1)")).getText(), is("2020/2021"));
    driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(2) > td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(2) > td:nth-child(2)")).getText(), is("104100002"));
    driver.findElement(By.id("Matriculas:Curso")).click();
    driver.findElement(By.id("Matriculas:Curso")).sendKeys("18/19");
    driver.findElement(By.id("Matriculas:idExp")).click();
    driver.findElement(By.id("Matriculas:idExp")).sendKeys("123");
    driver.findElement(By.id("Matriculas:botonBuscarMatricula")).click();
    driver.findElement(By.cssSelector("tbody:nth-child(2) td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) td:nth-child(1)")).getText(), is("18/19"));
    driver.findElement(By.cssSelector("tbody:nth-child(2) td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) td:nth-child(2)")).getText(), is("123"));
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tbody:nth-child(3) td:nth-child(1)"));
      assert(elements.size() == 0);
    }
    driver.findElement(By.cssSelector("td:nth-child(3) > .centrado")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) .centrado")).click();
    driver.findElement(By.cssSelector("table:nth-child(2) td:nth-child(1) > .centrado")).click();
    driver.findElement(By.cssSelector("td:nth-child(2) > .centrado")).click();
    driver.findElement(By.id("botonImportarOptativas")).click();
    driver.findElement(By.id("Optativas:archivooptativas:fileoptativas")).sendKeys("/home/alumno/eclipse-workspace/Secretaria/Secretaria-ejb/src/test/resources/Oferta asignaturas.xlsx");
    driver.findElement(By.id("Optativas:importarOptativa")).click();
    driver.findElement(By.id("botonImportarOptativas")).click();
    driver.findElement(By.cssSelector("td:nth-child(3) > .centrado")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(1)")).getText(), is("50659"));
    driver.findElement(By.id("Optativas:Optativa")).click();
    driver.findElement(By.id("Optativas:Optativa")).sendKeys("12346");
    driver.findElement(By.id("Optativas:botonBuscarOptativa")).click();
    driver.findElement(By.cssSelector("tbody:nth-child(2) td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) td:nth-child(1)")).getText(), is("12346"));
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tbody:nth-child(3) td:nth-child(1)"));
      assert(elements.size() == 0);
    }
    driver.findElement(By.cssSelector("td:nth-child(3) > .centrado")).click();
    driver.findElement(By.cssSelector("td:nth-child(4) > .centrado")).click();
    driver.findElement(By.cssSelector("table:nth-child(2) td:nth-child(1) > .centrado")).click();
    driver.findElement(By.cssSelector("td:nth-child(2) > .centrado")).click();
    driver.findElement(By.id("botonImportarUsuarios")).click();
    driver.findElement(By.id("Grupos:crearGrupos")).click();
    driver.findElement(By.id("botonImportarUsuarios")).click();
    driver.findElement(By.cssSelector("td:nth-child(2) > .centrado")).click();
    driver.findElement(By.id("Grupos:titulacion")).click();
    driver.findElement(By.id("Grupos:titulacion")).sendKeys("1041");
    driver.findElement(By.id("Grupos:curso")).click();
    driver.findElement(By.id("Grupos:curso")).sendKeys("2");
    driver.findElement(By.id("Grupos:letra")).click();
    driver.findElement(By.id("Grupos:letra")).sendKeys("A");
    driver.findElement(By.id("Grupos:botonBuscarGrupo")).click();
    driver.findElement(By.cssSelector("tbody:nth-child(2) td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) td:nth-child(1)")).getText(), is("1041"));
    driver.findElement(By.cssSelector("tbody:nth-child(2) td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) td:nth-child(2)")).getText(), is("2"));
    driver.findElement(By.cssSelector("tbody:nth-child(2) td:nth-child(3)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) td:nth-child(3)")).getText(), is("A"));
    driver.findElement(By.cssSelector("td:nth-child(2) > .centrado")).click();
    driver.findElement(By.cssSelector("td:nth-child(3) > .centrado")).click();
    driver.findElement(By.id("botonClases")).click();
    driver.findElement(By.cssSelector(".boton")).click();
    driver.findElement(By.cssSelector("table:nth-child(2) td:nth-child(1) > .centrado")).click();
    driver.findElement(By.cssSelector("td:nth-child(2) > .centrado")).click();
    driver.findElement(By.id("botonImportarClases")).click();
    driver.findElement(By.id("Clases:archivoclases:fileclases")).sendKeys("/home/alumno/eclipse-workspace/Secretaria/Secretaria-ejb/src/test/resources/horarios.csv");
    driver.findElement(By.id("Clases:importarClase")).click();
    driver.findElement(By.cssSelector("table:nth-child(2) td:nth-child(1) > .centrado")).click();
    driver.findElement(By.cssSelector("table:nth-child(1) td:nth-child(1) > .centrado")).click();
    driver.findElement(By.id("botonClases")).click();
    driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(1)")).getText(), is("1"));
    driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(2)")).getText(), is("A"));
    driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(3)")).click();
    assertThat(driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(3)")).getText(), is("12345"));
    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(5)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(5)")).getText(), is("2018-09-24"));
    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(6)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(6)")).getText(), is("10:45:00"));
    driver.findElement(By.cssSelector(".boton")).click();
    driver.findElement(By.id("botonClases")).click();
    driver.findElement(By.cssSelector(".boton")).click();
    driver.findElement(By.cssSelector("table:nth-child(2) td:nth-child(1) > .centrado")).click();
    driver.findElement(By.id("j_idt10:botonCerrarSesion")).click();
  }
}
